#!/usr/bin/env node
// compuute-scan v0.5.0 — MCP Server Security Scanner
// Compuute AB | daniel@compuute.se
// Zero external dependencies. Node.js built-ins only.
//
// Built from src/ modules by scripts/build.js
// Do not edit this file directly — edit src/*.js and run: npm run build

'use strict';

const fs = require('fs');
const path = require('path');


// ─────────────────────────────────────────────
// Constants
// ─────────────────────────────────────────────

const VERSION = '0.5.0';
const MAX_FILE_SIZE = 500 * 1024; // 500 KB
const MAX_CODE_SNIPPET = 120; // max characters in code/guardCode snippets
const GUARD_WINDOW = 15; // lines above/below to check for guards

const SCAN_EXTENSIONS = new Set([
  '.ts', '.js', '.py', '.mjs', '.cjs', '.tsx', '.jsx', '.go', '.rs',
]);

const SKIP_DIRS = new Set([
  'node_modules', '.git', 'dist', 'build', '__pycache__',
  'coverage', '.turbo', '.next', '.venv', 'venv', 'vendor',
]);

const SEVERITY_ORDER = { critical: 0, high: 1, medium: 2, low: 3, info: 4 };

// Inline suppression: place on the line ABOVE a finding to suppress it
// Supports: // compuute-scan-ignore-next-line
//           // compuute-scan-ignore-next-line L1-006
//           # compuute-scan-ignore-next-line (Python)
const IGNORE_PATTERN = /(?:\/\/|#)\s*compuute-scan-ignore-next-line(?:\s+(L\d+-\d+))?/;


// ─────────────────────────────────────────────
// Configuration
// ─────────────────────────────────────────────

function loadConfig(repoPath) {
  const configPath = path.join(repoPath, '.compuute-scan.json');
  if (!fs.existsSync(configPath)) return null;
  try {
    const raw = fs.readFileSync(configPath, 'utf-8');
    return JSON.parse(raw);
  } catch (err) {
    console.error(`[warn] Failed to parse .compuute-scan.json: ${err.message}`);
    return null;
  }
}

function shouldIgnoreFile(relPath, config) {
  if (!config || !config.ignore || !Array.isArray(config.ignore)) return false;
  for (const pattern of config.ignore) {
    // Simple glob: "test/**" matches "test/foo.js", "*.test.js" matches "bar.test.js"
    const re = new RegExp(
      '^' + pattern
        .replace(/\./g, '\\.')
        .replace(/\*\*/g, '(.+)')
        .replace(/\*/g, '([^/]+)')
      + '$'
    );
    if (re.test(relPath)) return true;
  }
  return false;
}

function applyRuleConfig(rules, config) {
  if (!config || !config.rules) return rules;
  return rules.filter(rule => {
    const override = config.rules[rule.id];
    if (!override) return true;
    if (override.enabled === false) return false;
    if (override.severity && SEVERITY_ORDER[override.severity] !== undefined) {
      rule.severity = override.severity;
    }
    return true;
  });
}


// ─────────────────────────────────────────────
// CLI Argument Parsing
// ─────────────────────────────────────────────

function parseArgs(argv) {
  const args = argv.slice(2);
  const opts = {
    repoPath: null,
    output: null,
    json: false,
    sarif: false,
    verbose: false,
    layer: null,    // filter by layer e.g. "L1"
    minSeverity: null,
    failOnSeverity: null,
    help: false,
  };

  for (let i = 0; i < args.length; i++) {
    const a = args[i];
    if (a === '--help' || a === '-h') { opts.help = true; }
    else if (a === '--json') { opts.json = true; }
    else if (a === '--sarif') { opts.sarif = true; }
    else if (a === '--verbose' || a === '-v') { opts.verbose = true; }
    else if (a === '--output' || a === '-o') { opts.output = args[++i]; }
    else if (a === '--layer') { opts.layer = args[++i]?.toUpperCase(); }
    else if (a === '--min-severity') { opts.minSeverity = args[++i]?.toLowerCase(); }
    else if (a === '--fail-on-severity') { opts.failOnSeverity = args[++i]?.toLowerCase(); }
    else if (!a.startsWith('-')) { opts.repoPath = a; }
  }

  return opts;
}

function printUsage() {
  console.log(`
compuute-scan v${VERSION} — MCP Server Security Scanner
Compuute AB | Internal Tool

Usage:
  compuute-scan <repo-path> [options]

Options:
  --output <file>         Write report to file
  --json                  Output JSON instead of markdown
  --sarif                 Output SARIF (GitHub Code Scanning)
  --verbose               Show files being scanned
  --layer <L0-L4>         Filter findings by layer
  --min-severity <s>      Filter: critical, high, medium, low
  --fail-on-severity <s>  Exit code 1 if findings >= severity (for CI)
  --help                  Show this message

Exit codes:
  0  No findings (or below --fail-on-severity threshold)
  1  Findings at or above --fail-on-severity threshold
  2  Scanner error (invalid path, etc.)

Examples:
  compuute-scan ./my-mcp-server
  compuute-scan ./server --output report.md
  compuute-scan ./server --json --output report.json
  compuute-scan ./server --sarif --output report.sarif
  compuute-scan ./server --layer L1 --min-severity high
  compuute-scan ./server --fail-on-severity high
`);
}


// ─────────────────────────────────────────────
// File Walker
// ─────────────────────────────────────────────

function walkDir(dir) {
  const files = [];
  let entries;
  try {
    entries = fs.readdirSync(dir, { withFileTypes: true });
  } catch {
    return files;
  }
  for (const entry of entries) {
    if (SKIP_DIRS.has(entry.name)) continue;
    if (entry.isSymbolicLink()) continue;
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...walkDir(full));
    } else if (entry.isFile() && SCAN_EXTENSIONS.has(path.extname(entry.name))) {
      try {
        const stat = fs.statSync(full);
        if (stat.size <= MAX_FILE_SIZE) {
          files.push(full);
        }
      } catch {
        // skip unreadable
      }
    }
  }
  return files;
}

function readFileSafe(filePath) {
  try {
    return fs.readFileSync(filePath, 'utf-8');
  } catch {
    return null;
  }
}


// ─────────────────────────────────────────────
// Guard Check System
// ─────────────────────────────────────────────

// Function definition patterns for boundary detection
const FUNC_DEF_PATTERNS = [
  // JS/TS: function name(...), async function, arrow functions assigned
  /^\s*(?:export\s+)?(?:async\s+)?function\s+\w+\s*\(/,
  /^\s*(?:export\s+)?(?:const|let|var)\s+\w+\s*=\s*(?:async\s+)?(?:\([^)]*\)|[a-zA-Z_]\w*)\s*=>/,
  /^\s*(?:async\s+)?(?:\w+)\s*\([^)]*\)\s*\{/,
  // Python: def name(
  /^\s*(?:async\s+)?def\s+\w+\s*\(/,
  // Go: func name(
  /^\s*func\s+(?:\([^)]*\)\s+)?\w+\s*\(/,
];

/**
 * Finds the enclosing function boundaries around a given line index.
 * Uses brace counting for JS/TS/Go and indent-based detection for Python.
 * Returns { start, end } line indices or null if not inside a function.
 */
function findFunctionBounds(lines, lineIdx) {
  // Walk backwards to find the nearest function definition
  let funcStart = -1;
  for (let i = lineIdx; i >= 0; i--) {
    for (const pat of FUNC_DEF_PATTERNS) {
      if (pat.test(lines[i])) {
        funcStart = i;
        break;
      }
    }
    if (funcStart >= 0) break;
  }
  if (funcStart < 0) return null;

  const funcLine = lines[funcStart];

  // Python: indent-based
  if (/^\s*(?:async\s+)?def\s+/.test(funcLine)) {
    const defIndent = funcLine.match(/^(\s*)/)[1].length;
    let funcEnd = funcStart;
    for (let i = funcStart + 1; i < lines.length; i++) {
      const trimmed = lines[i].trim();
      if (trimmed === '' || trimmed.startsWith('#')) { funcEnd = i; continue; }
      const indent = lines[i].match(/^(\s*)/)[1].length;
      if (indent <= defIndent) break;
      funcEnd = i;
    }
    return { start: funcStart, end: funcEnd };
  }

  // JS/TS/Go: brace-based
  let braceDepth = 0;
  let foundOpen = false;
  for (let i = funcStart; i < lines.length; i++) {
    const line = lines[i];
    for (let c = 0; c < line.length; c++) {
      if (line[c] === '{') { braceDepth++; foundOpen = true; }
      else if (line[c] === '}') { braceDepth--; }
    }
    if (foundOpen && braceDepth <= 0) {
      return { start: funcStart, end: i };
    }
  }
  // Unclosed — fallback to null
  return null;
}

/**
 * Checks if there's a mitigation/guard pattern near the matched line.
 * First tries function-boundary-aware search (entire enclosing function).
 * Falls back to GUARD_WINDOW lines above/below.
 * Returns { mitigated: bool, guardLine: number|null, guardCode: string|null }
 */
function checkGuard(lines, matchLineIdx, guardPatterns, guardWindow) {
  const window = guardWindow || GUARD_WINDOW;

  // Try function-boundary-aware search first
  const bounds = findFunctionBounds(lines, matchLineIdx);
  const start = bounds ? bounds.start : Math.max(0, matchLineIdx - window);
  const end = bounds ? bounds.end : Math.min(lines.length - 1, matchLineIdx + window);

  for (let i = start; i <= end; i++) {
    if (i === matchLineIdx) continue;
    const line = lines[i];
    for (const gp of guardPatterns) {
      if (gp.test(line)) {
        return {
          mitigated: true,
          guardLine: i + 1,
          guardCode: line.trim().substring(0, MAX_CODE_SNIPPET),
        };
      }
    }
  }
  return { mitigated: false, guardLine: null, guardCode: null };
}

function downgradeSeverity(severity) {
  const map = { critical: 'high', high: 'medium', medium: 'low', low: 'info' };
  return map[severity] || severity;
}


// ─────────────────────────────────────────────
// Security Rules — L1: SANDBOXING
// ─────────────────────────────────────────────

const L1_RULES = [
  {
    id: 'L1-001',
    title: 'eval() with non-literal argument',
    layer: 'L1',
    severity: 'critical',
    owasp: 'A03:2021 Injection',
    nis2: 'Art. 21(2)(e) — Secure development',
    description: 'eval() executes arbitrary code. If the argument is user-controlled, an attacker can execute arbitrary commands.',
    recommendation: 'Replace eval() with a safe parser or template engine. For JSON, use JSON.parse(). For math, use a sandboxed expression evaluator.',
    // Match eval( but not in comments
    test: (line) => {
      if (/^\s*\/\//.test(line) || /^\s*\*/.test(line) || /^\s*#/.test(line)) return false;
      // JS/Python eval — flag all eval() except eval('literal') with simple quotes
      // Template literals (backticks) with interpolation ARE dangerous
      if (!/\beval\s*\(/.test(line)) return false;
      // Only exclude eval('...') or eval("...") with simple string literals
      if (/\beval\s*\(\s*['"]/.test(line)) return false;
      return true;
    },
    guards: [/JSON\.parse/, /safeEval/, /sandbox/, /restricted/i],
  },
  {
    id: 'L1-002',
    title: 'Shell command execution (exec/spawn)',
    layer: 'L1',
    severity: 'critical',
    owasp: 'A03:2021 Injection',
    nis2: 'Art. 21(2)(e) — Secure development',
    description: 'exec/execSync/spawn can execute arbitrary shell commands. Use execFile with explicit arguments instead.',
    recommendation: 'Use child_process.execFile() or spawn() with an argument array (no shell interpolation). Never pass user input to exec().',
    test: (line) => {
      if (/^\s*\/\//.test(line) || /^\s*\*/.test(line) || /^\s*#/.test(line)) return false;
      // Exclude regex.exec(), mongoose .exec(), promise .exec(), query.exec()
      if (/\.exec\s*\(/.test(line)) {
        // Only flag child_process exec patterns
        if (/\bexec\s*\(/.test(line) && !/\w\.exec\s*\(/.test(line)) return true;
        return false;
      }
      if (/\bexecSync\s*\(/.test(line)) return true;
      if (/\bspawn\s*\(/.test(line) && /['"`]/.test(line)) {
        // spawn with string arg (not array)
        return true;
      }
      return false;
    },
    guards: [/execFile/, /escapeshell/i, /sanitize/i, /whitelist/i, /allowlist/i],
  },
  {
    id: 'L1-003',
    title: 'Python subprocess with shell=True',
    layer: 'L1',
    severity: 'critical',
    owasp: 'A03:2021 Injection',
    nis2: 'Art. 21(2)(e) — Secure development',
    description: 'subprocess with shell=True passes commands through the system shell, enabling command injection.',
    recommendation: 'Use subprocess.run() with a list of arguments and shell=False (the default).',
    test: (line) => {
      if (/^\s*#/.test(line)) return false;
      return /subprocess\.\w+\(.*shell\s*=\s*True/.test(line);
    },
    guards: [/shlex\.quote/, /shlex\.split/, /shell\s*=\s*False/],
  },
  {
    id: 'L1-004',
    title: 'Python os.system() call',
    layer: 'L1',
    severity: 'critical',
    owasp: 'A03:2021 Injection',
    nis2: 'Art. 21(2)(e) — Secure development',
    description: 'os.system() executes commands through the system shell with no input sanitization.',
    recommendation: 'Use subprocess.run() with explicit argument lists instead of os.system().',
    test: (line) => {
      if (/^\s*#/.test(line)) return false;
      return /\bos\.system\s*\(/.test(line);
    },
    guards: [/subprocess/, /shlex/],
  },
  {
    id: 'L1-005',
    title: 'Server binding to 0.0.0.0 (all interfaces)',
    layer: 'L1',
    severity: 'high',
    owasp: 'A05:2021 Security Misconfiguration',
    nis2: 'Art. 21(2)(d) — Network security',
    description: 'Binding to 0.0.0.0 exposes the server on all network interfaces, making it accessible from any network.',
    recommendation: 'Bind to 127.0.0.1 (localhost) unless external access is explicitly required. Use a reverse proxy for public exposure.',
    test: (line) => {
      if (/^\s*\/\//.test(line) || /^\s*#/.test(line)) return false;
      if (/['"]0\.0\.0\.0['"]/.test(line) && /(listen|bind|host|run)\s*[=(]/.test(line)) return true;
      if (/host\s*[:=]\s*['"]0\.0\.0\.0['"]/.test(line)) return true;
      // Go: ListenAndServe(":port", ...) — binds all interfaces
      if (/ListenAndServe\s*\(\s*["']:/.test(line)) return true;
      if (/net\.Listen\s*\(\s*["']tcp["']\s*,\s*["'](0\.0\.0\.0)?:/.test(line)) return true;
      return false;
    },
    guards: [/reverse.?proxy/i, /nginx/i, /traefik/i, /behind.*proxy/i, /127\.0\.0\.1/, /localhost/],
  },
  {
    id: 'L1-006',
    title: 'Path join without traversal validation',
    layer: 'L1',
    severity: 'high',
    owasp: 'A01:2021 Broken Access Control',
    nis2: 'Art. 21(2)(e) — Secure development',
    description: 'Using path.join/os.path.join with user input without validating the resolved path allows directory traversal attacks (../../etc/passwd).',
    recommendation: 'Resolve the full path with path.resolve()/os.path.realpath() and verify it starts with the expected base directory using startsWith().',
    test: (line) => {
      if (/^\s*\/\//.test(line) || /^\s*#/.test(line)) return false;
      if (/path\.join\s*\(/.test(line) || /os\.path\.join\s*\(/.test(line)) return true;
      // Go: filepath.Join
      if (/filepath\.Join\s*\(/.test(line)) return true;
      return false;
    },
    guards: [
      /startsWith/, /realpath/, /resolve/, /includes\s*\(\s*['"]\.\.['"]/,
      /throw/, /reject/, /Error/, /normalize/, /is_relative_to/,
      /commonpath/, /abspath/,
      // Go-specific guards
      /filepath\.Abs/, /filepath\.Clean/, /filepath\.Rel/,
      /strings\.HasPrefix/, /EvalSymlinks/, /filepath\.Base/,
    ],
  },
  {
    id: 'L1-007',
    title: 'File read with variable path (no validation)',
    layer: 'L1',
    severity: 'high',
    owasp: 'A01:2021 Broken Access Control',
    nis2: 'Art. 21(2)(e) — Secure development',
    description: 'Reading files with a user-controlled path without validation enables arbitrary file read attacks.',
    recommendation: 'Validate the resolved path starts with the expected base directory. Use a whitelist of allowed paths if possible.',
    test: (line) => {
      if (/^\s*\/\//.test(line) || /^\s*#/.test(line)) return false;
      // fs.readFile/readFileSync with a variable (not a literal string)
      if (/fs\.(readFile|readFileSync)\s*\(/.test(line) && !/fs\.(readFile|readFileSync)\s*\(\s*['"`]/.test(line)) return true;
      // Python open() with variable path
      if (/\bopen\s*\(/.test(line) && !/\bopen\s*\(\s*['"]/.test(line) && !/\.open\s*\(/.test(line)) {
        // Avoid matching things like file.open(), db.open()
        if (/^[^.]*\bopen\s*\(/.test(line.trim())) return true;
      }
      // Go: os.ReadFile, os.Open, os.Create with variable path
      if (/os\.(ReadFile|Open|Create|OpenFile|WriteFile)\s*\(/.test(line) && !/os\.(ReadFile|Open|Create|OpenFile|WriteFile)\s*\(\s*["'`]/.test(line)) return true;
      // Go: ioutil.ReadFile with variable
      if (/ioutil\.ReadFile\s*\(/.test(line) && !/ioutil\.ReadFile\s*\(\s*["'`]/.test(line)) return true;
      return false;
    },
    guards: [
      /startsWith/, /realpath/, /resolve/, /includes\s*\(\s*['"]\.\.['"]/,
      /throw/, /reject/, /Error/, /whitelist/i, /allowlist/i, /allowedPaths/i,
      /filepath\.Abs/, /filepath\.Clean/, /strings\.HasPrefix/, /EvalSymlinks/,
    ],
  },
  {
    id: 'L1-008',
    title: 'Python exec() — arbitrary code execution',
    layer: 'L1',
    severity: 'critical',
    owasp: 'A03:2021 Injection',
    nis2: 'Art. 21(2)(e) — Secure development',
    description: 'exec() executes arbitrary Python code. If user input reaches exec(), it enables full code execution.',
    recommendation: 'Avoid exec(). Use ast.literal_eval() for safe data parsing or a restricted execution environment.',
    test: (line) => {
      if (/^\s*#/.test(line)) return false;
      // Python exec() but not executor/execute/exec_command etc.
      if (/\bexec\s*\(/.test(line)) {
        // Exclude: executor, execute, exec_command, .exec(
        if (/execut/.test(line) || /exec_/.test(line) || /\.exec\s*\(/.test(line)) return false;
        return true;
      }
      return false;
    },
    guards: [/ast\.literal_eval/, /restricted/i, /sandbox/i],
  },
  {
    id: 'L1-009',
    title: 'Dynamic import/require with variable path',
    layer: 'L1',
    severity: 'high',
    owasp: 'A03:2021 Injection',
    nis2: 'Art. 21(2)(e) — Secure development',
    description: 'Dynamic import() or require() with a variable argument allows loading arbitrary modules at runtime. An attacker who controls the path can load malicious code.',
    recommendation: 'Use static imports or maintain an explicit allowlist of permitted module paths. Validate and sanitize any dynamic paths against a whitelist.',
    test: (line) => {
      if (/^\s*\/\//.test(line) || /^\s*\*/.test(line) || /^\s*#/.test(line)) return false;
      // import(variable) — not import('literal')
      if (/\bimport\s*\(/.test(line) && !/\bimport\s*\(\s*['"`]/.test(line)) return true;
      // require(variable) — not require('literal')
      if (/\brequire\s*\(/.test(line) && !/\brequire\s*\(\s*['"`]/.test(line)) return true;
      return false;
    },
    guards: [/allowlist/i, /whitelist/i, /allowedModules/i, /safeRequire/i, /validateModule/i],
  },
  {
    id: 'L1-010',
    title: 'Wildcard CORS origin (Access-Control-Allow-Origin: *)',
    layer: 'L1',
    severity: 'high',
    owasp: 'A05:2021 Security Misconfiguration',
    nis2: 'Art. 21(2)(d) — Network security',
    description: 'Setting Access-Control-Allow-Origin to "*" allows any website to make cross-origin requests to this MCP server. Combined with credentials, this enables cross-site data theft.',
    recommendation: 'Restrict CORS to specific trusted origins. Never use wildcard CORS on authenticated endpoints. Use an allowlist of permitted origins.',
    test: (line) => {
      if (/^\s*\/\//.test(line) || /^\s*\*/.test(line) || /^\s*#/.test(line)) return false;
      // cors({ origin: '*' }) or cors() with no args (defaults to *)
      if (/\bcors\s*\(\s*\)/.test(line)) return true;
      if (/origin\s*[:=]\s*['"`]\*['"`]/.test(line)) return true;
      // Access-Control-Allow-Origin header set to *
      if (/['"`]Access-Control-Allow-Origin['"`]\s*,\s*['"`]\*['"`]/.test(line)) return true;
      if (/['"]\*['"]\s*\)/.test(line) && /setHeader|header\s*\(/.test(line) && /Access.Control.Allow.Origin/.test(line)) return true;
      return false;
    },
    guards: [/allowedOrigins/i, /originWhitelist/i, /corsOptions/i, /origin.*!==.*\*/, /validateOrigin/i],
  },
  {
    id: 'L1-012',
    title: 'Pickle deserialization (arbitrary code execution)',
    layer: 'L1',
    severity: 'critical',
    owasp: 'A08:2021 Software and Data Integrity Failures',
    nis2: 'Art. 21(2)(e) — Secure development',
    description: 'pickle.load/loads deserializes arbitrary Python objects and can execute code during unpickling. An attacker who controls the input can achieve full remote code execution.',
    recommendation: 'Never unpickle untrusted data. Use json, msgpack, or protobuf instead. If pickle is required, use hmac-signed payloads and restrict classes via RestrictedUnpickler.',
    test: (line) => {
      if (/^\s*#/.test(line)) return false;
      return /\bpickle\.(loads?|Unpickler)\s*\(/.test(line) || /\bdill\.loads?\s*\(/.test(line) || /\bmarshal\.loads?\s*\(/.test(line);
    },
    guards: [/hmac/i, /RestrictedUnpickler/i, /json\.loads/i, /verify.*signature/i, /trusted/i],
  },
  {
    id: 'L1-013',
    title: 'YAML unsafe load (code execution)',
    layer: 'L1',
    severity: 'critical',
    owasp: 'A08:2021 Software and Data Integrity Failures',
    nis2: 'Art. 21(2)(e) — Secure development',
    description: 'yaml.load() without SafeLoader can instantiate arbitrary Python objects, leading to remote code execution. yaml.unsafe_load() is explicitly dangerous.',
    recommendation: 'Use yaml.safe_load() or yaml.load(data, Loader=yaml.SafeLoader). Never use yaml.load() with untrusted input without specifying a safe Loader.',
    test: (line) => {
      if (/^\s*#/.test(line)) return false;
      if (/yaml\.unsafe_load\s*\(/.test(line)) return true;
      // yaml.load( without SafeLoader/safe_load
      if (/yaml\.load\s*\(/.test(line) && !/SafeLoader|safe_load|BaseLoader|FullLoader/.test(line)) return true;
      return false;
    },
    guards: [/safe_load/, /SafeLoader/, /BaseLoader/],
  },
  {
    id: 'L1-014',
    title: 'SQL injection via Python f-string or format',
    layer: 'L1',
    severity: 'critical',
    owasp: 'A03:2021 Injection',
    nis2: 'Art. 21(2)(e) — Secure development',
    description: 'Building SQL queries with f-strings, %-formatting, or string concatenation allows SQL injection when user input is interpolated directly into the query.',
    recommendation: 'Use parameterized queries: cursor.execute("SELECT * FROM t WHERE id = ?", (user_id,)). With ORMs, use the query builder instead of raw SQL strings.',
    test: (line) => {
      if (/^\s*#/.test(line)) return false;
      // cursor.execute(f"...") or .execute(f"...")
      if (/\.execute\s*\(\s*f['"`]/.test(line)) return true;
      // cursor.execute("..." % var) — %-formatting
      if (/\.execute\s*\(\s*['"`].*%s/.test(line) && /%\s*\(/.test(line)) return true;
      // cursor.execute("..." + var + "...")
      if (/\.execute\s*\(\s*['"`].*\+/.test(line) && /SELECT|INSERT|UPDATE|DELETE|WHERE/i.test(line)) return true;
      return false;
    },
    guards: [/parameterized/i, /prepared/i, /placeholder/i, /\?\s*,/, /%s.*,\s*\(/, /sqlalchemy/i],
  },
  {
    id: 'L1-015',
    title: 'SSL/TLS verification disabled',
    layer: 'L1',
    severity: 'high',
    owasp: 'A02:2021 Cryptographic Failures',
    nis2: 'Art. 21(2)(h) — Cryptography and encryption',
    description: 'Disabling SSL/TLS certificate verification (verify=False, ssl=False) allows man-in-the-middle attacks. All outbound HTTPS connections should validate certificates.',
    recommendation: 'Remove verify=False / ssl=False. Use proper CA certificates (certifi). If using self-signed certs in development, restrict to dev environments only.',
    test: (line) => {
      if (/^\s*#/.test(line) || /^\s*\/\//.test(line)) return false;
      // Python: verify=False
      if (/verify\s*=\s*False/.test(line) && /\.(get|post|put|delete|patch|request|fetch)\s*\(/.test(line)) return true;
      // Python aiohttp: ssl=False
      if (/ssl\s*=\s*False/.test(line)) return true;
      // Node.js: rejectUnauthorized: false
      if (/rejectUnauthorized\s*:\s*false/.test(line)) return true;
      // NODE_TLS_REJECT_UNAUTHORIZED = '0'
      if (/NODE_TLS_REJECT_UNAUTHORIZED/.test(line) && /['"`]0['"`]/.test(line)) return true;
      return false;
    },
    guards: [/certifi/i, /NODE_ENV.*production/i, /development/i, /process\.env\.NODE_TLS/],
  },
  {
    id: 'L1-016',
    title: 'Insecure random used for security purpose',
    layer: 'L1',
    severity: 'high',
    owasp: 'A02:2021 Cryptographic Failures',
    nis2: 'Art. 21(2)(h) — Cryptography and encryption',
    description: 'Using Math.random() (JS), Python random module, or Go math/rand for tokens, keys, or secrets produces predictable values. These PRNGs are not cryptographically secure.',
    recommendation: 'Use crypto.randomBytes/randomUUID (Node.js), secrets.token_hex (Python), or crypto/rand (Go) for any security-sensitive random values.',
    test: (line) => {
      if (/^\s*#/.test(line) || /^\s*\/\//.test(line)) return false;
      const hasWeakRandom = /\b(Math\.random|random\.(choice|choices|randint|sample|random)|rand\.(Intn|Int31|Int63|Float64|Read))\s*\(/.test(line);
      const hasSecurityContext = /\b(token|key|secret|password|nonce|salt|session|csrf|otp|code)\b/i.test(line);
      return hasWeakRandom && hasSecurityContext;
    },
    guards: [/crypto\.randomBytes/, /crypto\.randomUUID/, /\bsecrets\./, /crypto\.getRandomValues/, /crypto\/rand/, /uuid/i],
  },
  {
    id: 'L1-017',
    title: 'Python CORS wildcard (Starlette/FastAPI)',
    layer: 'L1',
    severity: 'high',
    owasp: 'A05:2021 Security Misconfiguration',
    nis2: 'Art. 21(2)(d) — Network security',
    description: 'Setting allow_origins=["*"] in Starlette/FastAPI CORSMiddleware allows any website to make cross-origin requests to this MCP server.',
    recommendation: 'Restrict allow_origins to specific trusted domains. Never use wildcard CORS on MCP servers that handle authenticated requests.',
    test: (line) => {
      if (/^\s*#/.test(line)) return false;
      // allow_origins=["*"] or allow_origins=['*']
      if (/allow_origins\s*=\s*\[.*['"`]\*['"`]/.test(line)) return true;
      return false;
    },
    guards: [/allow_origins\s*=\s*\[.*(?!['"`]\*['"`])['"`]https?:/, /allowedOrigins/i, /CORS_ORIGINS/i],
  },
  {
    id: 'L1-018',
    title: 'Go exec.Command with string concatenation',
    layer: 'L1',
    severity: 'critical',
    owasp: 'A03:2021 Injection',
    nis2: 'Art. 21(2)(e) — Secure development',
    description: 'Using exec.Command with fmt.Sprintf or string concatenation enables shell injection if user input is interpolated. Go exec.Command does not use a shell by default, but passing concatenated strings to "/bin/sh -c" re-introduces the risk.',
    recommendation: 'Pass arguments as separate parameters to exec.Command (arg-per-slot). Never use fmt.Sprintf to build command strings. Avoid "/bin/sh", "-c" with user input.',
    test: (line) => {
      if (/^\s*\/\//.test(line)) return false;
      // exec.Command with sh -c or bash -c
      if (/exec\.Command\s*\(/.test(line) && /(sh|bash|cmd)/.test(line)) return true;
      // exec.Command with fmt.Sprintf
      if (/exec\.Command\s*\(\s*fmt\.Sprintf/.test(line)) return true;
      // exec.CommandContext with shell
      if (/exec\.CommandContext\s*\(/.test(line) && /(sh|bash|cmd)/.test(line)) return true;
      return false;
    },
    guards: [/shellescape/i, /shlex/i, /safeCommand/i, /allowedCommands/i, /whitelist/i],
  },
  {
    id: 'L1-019',
    title: 'Go text/template used for HTML (XSS risk)',
    layer: 'L1',
    severity: 'high',
    owasp: 'A03:2021 Injection',
    nis2: 'Art. 21(2)(e) — Secure development',
    description: 'Go text/template does not escape HTML. If used to render web content, user input can inject arbitrary HTML/JavaScript (XSS).',
    recommendation: 'Use html/template instead of text/template for any HTML output. html/template provides contextual auto-escaping.',
    test: (line) => {
      if (/^\s*\/\//.test(line)) return false;
      return /["']text\/template["']/.test(line);
    },
    guards: [/html\/template/, /template\.HTMLEscapeString/, /bluemonday/i, /sanitize/i],
    contextCheck: (lines, idx) => {
      const start = Math.max(0, idx - 10);
      const end = Math.min(lines.length - 1, idx + 10);
      for (let i = start; i <= end; i++) {
        if (/\b(html|HTML|web|http|response|ResponseWriter|ServeHTTP)\b/.test(lines[i])) return true;
      }
      return false;
    },
  },
  {
    id: 'L1-020',
    title: 'Go SQL query with fmt.Sprintf (injection risk)',
    layer: 'L1',
    severity: 'critical',
    owasp: 'A03:2021 Injection',
    nis2: 'Art. 21(2)(e) — Secure development',
    description: 'Building SQL queries with fmt.Sprintf or string concatenation in Go allows SQL injection when user input is interpolated.',
    recommendation: 'Use parameterized queries: db.Query("SELECT * FROM t WHERE id = $1", id). Use sqlx or GORM query builders for complex queries.',
    test: (line) => {
      if (/^\s*\/\//.test(line)) return false;
      // db.Query/Exec/QueryRow with fmt.Sprintf
      if (/\.(Query|Exec|QueryRow|QueryContext|ExecContext)\s*\(\s*fmt\.Sprintf/.test(line)) return true;
      // db.Query with string concat (+)
      if (/\.(Query|Exec|QueryRow)\s*\(.*\+/.test(line) && /SELECT|INSERT|UPDATE|DELETE|WHERE/i.test(line)) return true;
      return false;
    },
    guards: [/\$\d/, /\?\s*,/, /squirrel/i, /sqlx\.Named/i, /Prepare\s*\(/, /parameterized/i],
  },
  {
    id: 'L1-021',
    title: 'Go TLS InsecureSkipVerify enabled',
    layer: 'L1',
    severity: 'high',
    owasp: 'A02:2021 Cryptographic Failures',
    nis2: 'Art. 21(2)(h) — Cryptography and encryption',
    description: 'Setting InsecureSkipVerify: true disables TLS certificate validation, enabling man-in-the-middle attacks on all outbound HTTPS connections.',
    recommendation: 'Remove InsecureSkipVerify: true. Use proper CA certificates. If using self-signed certs in development, restrict via build tags or environment checks.',
    test: (line) => {
      if (/^\s*\/\//.test(line)) return false;
      return /InsecureSkipVerify\s*:\s*true/.test(line);
    },
    guards: [/development/i, /testing/i, /\.env/i, /os\.Getenv/],
  },
  {
    id: 'L1-022',
    title: 'Go CORS wildcard (rs/cors or manual header)',
    layer: 'L1',
    severity: 'high',
    owasp: 'A05:2021 Security Misconfiguration',
    nis2: 'Art. 21(2)(d) — Network security',
    description: 'Setting AllowedOrigins to ["*"] or AllowAll() in Go CORS middleware allows any website to make cross-origin requests.',
    recommendation: 'Restrict AllowedOrigins to specific trusted domains. Use cors.Options{AllowedOrigins: []string{"https://app.example.com"}}.',
    test: (line) => {
      if (/^\s*\/\//.test(line)) return false;
      // cors.AllowAll() or cors.Default()
      if (/cors\.(AllowAll|Default)\s*\(/.test(line)) return true;
      // AllowedOrigins: []string{"*"}
      if (/AllowedOrigins.*\*/.test(line)) return true;
      // Manual header set
      if (/Set.*Header.*Access-Control-Allow-Origin.*\*/.test(line)) return true;
      return false;
    },
    guards: [/AllowedOrigins.*https?:/, /isAllowedOrigin/i, /originValidator/i],
  },

  // ─── Rust Rules ───

  {
    id: 'L1-023',
    title: 'Rust unsafe block',
    layer: 'L1',
    severity: 'high',
    owasp: 'A03:2021 Injection',
    nis2: 'Art. 21(2)(e) — Secure development',
    description: 'unsafe {} blocks bypass Rust memory safety guarantees. In MCP servers this can lead to buffer overflows, use-after-free, and other memory corruption vulnerabilities exploitable by untrusted input.',
    recommendation: 'Avoid unsafe blocks. Use safe abstractions from the standard library or well-audited crates. If unavoidable, add #[deny(unsafe_code)] at the crate level and document why each unsafe block is sound.',
    test: (line) => {
      if (/^\s*\/\//.test(line)) return false;
      return /\bunsafe\s*\{/.test(line);
    },
    guards: [/deny\(unsafe_code\)/, /SAFETY:/, /Safety:/, /# Safety/, /\bvalidate\b/i],
  },
  {
    id: 'L1-024',
    title: 'Rust Command::new with user input',
    layer: 'L1',
    severity: 'critical',
    owasp: 'A03:2021 Injection',
    nis2: 'Art. 21(2)(e) — Secure development',
    description: 'std::process::Command::new() with format! or user-controlled strings enables command injection. Unlike Go, Rust Command bypasses the shell by default, but shell injection is still possible via /bin/sh -c.',
    recommendation: 'Pass arguments via .arg() instead of building command strings. Never use format! to construct command arguments. Validate input against an allowlist.',
    test: (line) => {
      if (/^\s*\/\//.test(line)) return false;
      // Command::new with format! or variable (not literal)
      if (/Command::new\s*\(\s*format!/.test(line)) return true;
      if (/Command::new\s*\(\s*&?format!/.test(line)) return true;
      // Command::new("sh") or Command::new("bash")
      if (/Command::new\s*\(\s*"(sh|bash|cmd)"/.test(line)) return true;
      return false;
    },
    guards: [/\.arg\s*\(/, /allowlist/i, /whitelist/i, /validate/i],
  },
  {
    id: 'L1-025',
    title: 'Rust SQL query with format!',
    layer: 'L1',
    severity: 'critical',
    owasp: 'A03:2021 Injection',
    nis2: 'Art. 21(2)(e) — Secure development',
    description: 'Building SQL queries with format!() in Rust enables SQL injection when user input is interpolated directly into the query string.',
    recommendation: 'Use parameterized queries with sqlx::query!() or diesel query builder. Never use format! to build SQL strings with user input.',
    test: (line) => {
      if (/^\s*\/\//.test(line)) return false;
      // .query(&format!("...")) or .execute(&format!("..."))
      if (/\.(query|execute|query_as|fetch_one|fetch_all)\s*\(\s*&?format!/.test(line)) return true;
      // sqlx::query(format!(...))
      if (/query\s*\(\s*&?format!\s*\(/.test(line) && /SELECT|INSERT|UPDATE|DELETE|WHERE/i.test(line)) return true;
      return false;
    },
    guards: [/sqlx::query!/, /query!\s*\(/, /diesel/, /prepared/i, /parameterized/i, /bind\s*\(/],
  },
  {
    id: 'L1-026',
    title: 'Rust TLS certificate verification disabled',
    layer: 'L1',
    severity: 'high',
    owasp: 'A02:2021 Cryptographic Failures',
    nis2: 'Art. 21(2)(h) — Cryptography and encryption',
    description: 'danger_accept_invalid_certs(true) disables TLS certificate validation in reqwest/rustls, enabling man-in-the-middle attacks.',
    recommendation: 'Remove danger_accept_invalid_certs(true). Use proper CA certificates. If self-signed certs are needed for development, restrict via compile-time feature flags.',
    test: (line) => {
      if (/^\s*\/\//.test(line)) return false;
      return /danger_accept_invalid_certs\s*\(\s*true\s*\)/.test(line);
    },
    guards: [/development/i, /testing/i, /cfg!\s*\(\s*debug_assertions/, /cfg!\s*\(\s*test/],
  },
];

// Negative check rules for L1 (whole-codebase checks)
const L1_NEGATIVE_RULES = [
  {
    id: 'L1-011',
    title: 'No security headers middleware detected',
    layer: 'L1',
    severity: 'medium',
    owasp: 'A05:2021 Security Misconfiguration',
    nis2: 'Art. 21(2)(d) — Network security',
    description: 'No security headers middleware (helmet, secure-headers) or manual security header configuration was detected. HTTP-exposed MCP servers should set Content-Security-Policy, X-Content-Type-Options, Strict-Transport-Security, and other protective headers.',
    recommendation: 'Add helmet (Node.js) or secure-headers middleware. At minimum set: Content-Security-Policy, X-Content-Type-Options: nosniff, Strict-Transport-Security, X-Frame-Options: DENY.',
    pattern: /\b(helmet|secureHeaders|secure.headers|Content-Security-Policy|X-Content-Type-Options|Strict-Transport-Security|X-Frame-Options|nosniff)\b/i,
  },
  {
    id: 'L1-027',
    title: 'Rust crate missing #[deny(unsafe_code)]',
    layer: 'L1',
    severity: 'medium',
    owasp: 'A05:2021 Security Misconfiguration',
    nis2: 'Art. 21(2)(e) — Secure development',
    description: 'The crate does not have #[deny(unsafe_code)] or #![forbid(unsafe_code)] at the crate level. Without this, unsafe blocks can be added without triggering a compile error.',
    recommendation: 'Add #![forbid(unsafe_code)] or #![deny(unsafe_code)] at the top of lib.rs/main.rs to enforce memory safety at the crate level.',
    pattern: /#!\[(?:deny|forbid)\s*\(\s*unsafe_code\s*\)\]/,
    // Only fire for Rust projects (detected by Cargo.toml presence)
    contextRequired: 'rust',
  },
];



// ─────────────────────────────────────────────
// L2-L4 rules available in Compuute Professional Audit
// https://compuute.se/audit
// ─────────────────────────────────────────────

const L2_RULES = [];
const L2_NEGATIVE_RULES = [];
const L3_RULES = [];
const L3_NEGATIVE_RULES = [];
const L4_RULES = [];
const L4_NEGATIVE_RULES = [];
const L4_RULES_EXTRA = [];


// ─────────────────────────────────────────────
// L0: DISCOVERY
// ─────────────────────────────────────────────

function runL0Discovery(repoPath, allContent, sourceFiles) {
  const discovery = {
    totalSourceFiles: sourceFiles.length,
    transports: [],
    toolCount: 0,
    hasDependencyPinning: false,
    hasContainerization: false,
    dependencies: [],
    dependencyFile: null,
  };

  // Detect transports
  const transportPatterns = [
    { name: 'stdio', pattern: /\b(stdio|StdioServerTransport|stdio_server|NewStdioServer|server\.ServeStdio)\b/ },
    { name: 'SSE', pattern: /\b(SSEServerTransport|SseServerTransport|sse|NewSSEServer|SSEHandler)\b/i },
    { name: 'Streamable HTTP', pattern: /\b(StreamableHTTPServerTransport|httpStream|streamable.http|StreamableHTTP)\b/ },
  ];
  for (const tp of transportPatterns) {
    if (tp.pattern.test(allContent)) {
      discovery.transports.push(tp.name);
    }
  }

  // Count MCP tools
  const toolPatterns = [
    /name\s*:\s*['"`]/g,
    /tools\/list/g,
    /registerTool/g,
    /\.tool\s*\(/g,
    /\.action\s*\(/g,
    /\.query\s*\(/g,
    /\.mutation\s*\(/g,
    /@\w+\.tool\s*\(/g,                // Python FastMCP decorator
    /@server\.call_tool\s*\(/g,         // Python low-level MCP
    /@server\.list_tools\s*\(/g,        // Python low-level MCP
    /AddTool\s*\(/g,                    // Go mcp-go
    /NewTool\s*\(/g,                    // Go mcp-go
    /server\.HandleFunc\s*\(/g,         // Go MCP handler
  ];
  let maxToolCount = 0;
  for (const tp of toolPatterns) {
    const matches = allContent.match(tp);
    if (matches && matches.length > maxToolCount) {
      maxToolCount = matches.length;
    }
  }
  discovery.toolCount = maxToolCount;

  // Dependency pinning
  const lockFiles = ['package-lock.json', 'pnpm-lock.yaml', 'yarn.lock', 'requirements.txt', 'poetry.lock', 'go.sum'];
  for (const lf of lockFiles) {
    if (fs.existsSync(path.join(repoPath, lf))) {
      discovery.hasDependencyPinning = true;
      break;
    }
  }

  // Containerization
  const containerFiles = ['Dockerfile', 'docker-compose.yml', 'docker-compose.yaml'];
  for (const cf of containerFiles) {
    if (fs.existsSync(path.join(repoPath, cf))) {
      discovery.hasContainerization = true;
      break;
    }
  }

  // List dependencies
  const pkgJsonPath = path.join(repoPath, 'package.json');
  if (fs.existsSync(pkgJsonPath)) {
    try {
      const pkg = JSON.parse(fs.readFileSync(pkgJsonPath, 'utf-8'));
      const deps = { ...pkg.dependencies, ...pkg.devDependencies };
      discovery.dependencies = Object.entries(deps).map(([name, ver]) => `${name}@${ver}`);
      discovery.dependencyFile = 'package.json';
    } catch (err) {
      console.error(`[warn] Failed to parse package.json: ${err.message}`);
    }
  }

  const reqTxtPath = path.join(repoPath, 'requirements.txt');
  if (fs.existsSync(reqTxtPath)) {
    try {
      const content = fs.readFileSync(reqTxtPath, 'utf-8');
      discovery.dependencies = content.split('\n').filter(l => l.trim() && !l.startsWith('#'));
      discovery.dependencyFile = 'requirements.txt';
    } catch (err) {
      console.error(`[warn] Failed to parse requirements.txt: ${err.message}`);
    }
  }

  // Python pyproject.toml dependencies
  const pyprojectPath = path.join(repoPath, 'pyproject.toml');
  if (fs.existsSync(pyprojectPath) && !discovery.dependencyFile) {
    try {
      const content = fs.readFileSync(pyprojectPath, 'utf-8');
      const deps = [];
      const depMatches = content.match(/["']([a-zA-Z0-9_-]+(?:\[[\w,]+\])?(?:[><=!~]+[^"']+)?)["']/g);
      if (depMatches) {
        for (const m of depMatches) {
          const cleaned = m.replace(/["']/g, '');
          if (cleaned.length > 1 && !/^(python|readme|license|description|name|version|author|url|homepage|repository)$/i.test(cleaned)) {
            deps.push(cleaned);
          }
        }
      }
      if (deps.length > 0) {
        discovery.dependencies = deps;
        discovery.dependencyFile = 'pyproject.toml';
      }
    } catch (err) {
      console.error(`[warn] Failed to parse pyproject.toml: ${err.message}`);
    }
  }

  // Python lock files for dependency pinning
  const pyLockFiles = ['poetry.lock', 'uv.lock', 'Pipfile.lock'];
  for (const lf of pyLockFiles) {
    if (fs.existsSync(path.join(repoPath, lf))) {
      discovery.hasDependencyPinning = true;
      break;
    }
  }

  // Go go.mod dependencies
  const goModPath = path.join(repoPath, 'go.mod');
  if (fs.existsSync(goModPath) && !discovery.dependencyFile) {
    try {
      const content = fs.readFileSync(goModPath, 'utf-8');
      const deps = [];
      const requireBlock = content.match(/require\s*\(([\s\S]*?)\)/);
      if (requireBlock) {
        for (const line of requireBlock[1].split('\n')) {
          const m = line.trim().match(/^(\S+)\s+(\S+)/);
          if (m && !m[1].startsWith('//')) deps.push(`${m[1]}@${m[2]}`);
        }
      }
      for (const m of content.matchAll(/require\s+(\S+)\s+(v\S+)/g)) {
        if (!deps.some(d => d.startsWith(m[1]))) deps.push(`${m[1]}@${m[2]}`);
      }
      if (deps.length > 0) {
        discovery.dependencies = deps;
        discovery.dependencyFile = 'go.mod';
      }
    } catch (err) {
      console.error(`[warn] Failed to parse go.mod: ${err.message}`);
    }
  }

  // Rust Cargo.toml dependencies
  const cargoPath = path.join(repoPath, 'Cargo.toml');
  if (fs.existsSync(cargoPath) && !discovery.dependencyFile) {
    try {
      const content = fs.readFileSync(cargoPath, 'utf-8');
      const deps = [];
      // Parse [dependencies] section (simple TOML parsing, no external deps)
      const depSections = content.matchAll(/\[(?:dev-)?dependencies(?:\.[^\]]+)?\]\s*\n([\s\S]*?)(?=\n\[|\n*$)/g);
      for (const section of depSections) {
        for (const line of section[1].split('\n')) {
          const trimmed = line.trim();
          if (!trimmed || trimmed.startsWith('#')) continue;
          // name = "version" or name = { version = "..." }
          const simple = trimmed.match(/^(\S+)\s*=\s*"([^"]+)"/);
          if (simple) { deps.push(`${simple[1]}@${simple[2]}`); continue; }
          const table = trimmed.match(/^(\S+)\s*=\s*\{.*version\s*=\s*"([^"]+)"/);
          if (table) deps.push(`${table[1]}@${table[2]}`);
        }
      }
      if (deps.length > 0) {
        discovery.dependencies = deps;
        discovery.dependencyFile = 'Cargo.toml';
      }
    } catch (err) {
      console.error(`[warn] Failed to parse Cargo.toml: ${err.message}`);
    }
  }

  return discovery;
}





// ─────────────────────────────────────────────
// Main Scan Engine
// ─────────────────────────────────────────────

function makeFinding(rule, file, line, code, guard) {
  return {
    id: rule.id,
    title: rule.title,
    layer: rule.layer,
    severity: guard?.mitigated ? downgradeSeverity(rule.severity) : rule.severity,
    owasp: rule.owasp,
    nis2: rule.nis2,
    gdpr: rule.gdpr || null,
    dora: rule.dora || null,
    file,
    line,
    code,
    mitigated: guard?.mitigated || false,
    guardLine: guard?.guardLine || null,
    guardCode: guard?.guardCode || null,
    description: rule.description,
    recommendation: rule.recommendation,
  };
}

function scanFile(filePath, repoPath, allRules, guardWindow) {
  const content = readFileSafe(filePath);
  if (!content) return [];

  const lines = content.split('\n');
  const relPath = path.relative(repoPath, filePath);
  const findings = [];

  for (const rule of allRules) {
    // Count-based detection: fires when pattern exceeds N occurrences in a file
    if (rule.countThreshold) {
      let count = 0;
      for (let i = 0; i < lines.length; i++) {
        if (rule.test && rule.test(lines[i])) count++;
      }
      if (count > rule.countThreshold) {
        findings.push(makeFinding(rule, relPath, null, `${count} occurrences found`));
      }
      continue;
    }

    for (let i = 0; i < lines.length; i++) {
      let matched = false;

      if (rule.test) {
        matched = rule.test(lines[i]);
      } else if (rule.multiLineTest) {
        matched = rule.multiLineTest(lines, i);
      }

      if (!matched) continue;
      if (rule.contextCheck && !rule.contextCheck(lines, i)) continue;

      // Check for inline ignore comment on the line above
      if (i > 0) {
        const ignoreMatch = IGNORE_PATTERN.exec(lines[i - 1]);
        if (ignoreMatch) {
          const ignoreRuleId = ignoreMatch[1];
          if (!ignoreRuleId || ignoreRuleId === rule.id) continue;
        }
      }

      const guard = (rule.guards && rule.guards.length > 0)
        ? checkGuard(lines, i, rule.guards, guardWindow)
        : null;

      findings.push(makeFinding(rule, relPath, i + 1, lines[i].trim().substring(0, MAX_CODE_SNIPPET), guard));
    }
  }

  return findings;
}

function runNegativeChecks(allContent, negativeRules, sourceFiles) {
  const findings = [];
  const hasRust = sourceFiles ? sourceFiles.some(f => f.endsWith('.rs')) : false;
  for (const rule of negativeRules) {
    // Skip context-specific rules when context doesn't apply
    if (rule.contextRequired === 'rust' && !hasRust) continue;
    if (!rule.pattern.test(allContent)) {
      findings.push(makeFinding(rule, '(entire codebase)', null, 'Pattern not found in any source file'));
    }
  }
  return findings;
}





// ─────────────────────────────────────────────
// Report: Markdown
// ─────────────────────────────────────────────

function summarizeFindings(findings) {
  const summary = { critical: 0, high: 0, medium: 0, low: 0, info: 0 };
  const layers = {};
  for (const f of findings) {
    summary[f.severity] = (summary[f.severity] || 0) + 1;
    layers[f.layer] = (layers[f.layer] || 0) + 1;
  }
  return { summary, layers };
}

function generateMarkdownReport(repoPath, findings, discovery, durationMs) {
  const repoName = path.basename(path.resolve(repoPath));
  const date = new Date().toISOString().split('T')[0];
  const filesScanned = discovery.totalSourceFiles;
  const { summary, layers } = summarizeFindings(findings);

  function layerEmoji(count) {
    if (count === 0 || count === undefined) return '\u2705';
    if (count <= 2) return '\u26A0\uFE0F';
    return '\uD83D\uDD34';
  }

  const layerDescriptions = {
    L0: 'Discovery & Metadata',
    L1: 'Sandboxing & Code Execution',
    L2: 'Authorization & Secrets',
    L3: 'Tool Integrity & Data Handling',
    L4: 'Monitoring & Logging',
  };

  const severityOrder = ['critical', 'high', 'medium', 'low', 'info'];
  const severityLabels = {
    critical: '\uD83D\uDD34 CRITICAL',
    high: '\uD83D\uDFE0 HIGH',
    medium: '\uD83D\uDFE1 MEDIUM',
    low: '\uD83D\uDFE2 LOW',
    info: '\u2139\uFE0F INFO',
  };

  const p = [];

  // Header
  p.push(`# MCP Security Scan Report\n`);
  p.push(`| Field | Value |\n|-------|-------|`);
  p.push(`| **Repository** | \`${repoName}\` |`);
  p.push(`| **Date** | ${date} |`);
  p.push(`| **Files Scanned** | ${filesScanned} |`);
  p.push(`| **Scan Duration** | ${(durationMs / 1000).toFixed(2)}s |`);
  p.push(`| **Scanner** | compuute-scan v${VERSION} |\n`);

  // Executive Summary
  p.push(`## Executive Summary\n`);
  p.push(`| Severity | Count |\n|----------|-------|`);
  p.push(`| \uD83D\uDD34 Critical | ${summary.critical} |`);
  p.push(`| \uD83D\uDFE0 High | ${summary.high} |`);
  p.push(`| \uD83D\uDFE1 Medium | ${summary.medium} |`);
  p.push(`| \uD83D\uDFE2 Low | ${summary.low} |`);
  p.push(`| Total | ${findings.length} |\n`);

  // Layer Assessment
  p.push(`## Layer Assessment\n`);
  p.push(`| Layer | Status | Findings | Description |\n|-------|--------|----------|-------------|`);
  for (const l of ['L0', 'L1']) {
    const count = layers[l] || 0;
    p.push(`| ${l} | ${layerEmoji(count)} | ${count} | ${layerDescriptions[l]} |`);
  }
  p.push(`| L2-L4 | — | — | [Available in Compuute Professional Audit](https://compuute.se/audit) |\n`);

  // Detailed Findings (grouped by severity)
  p.push(`## Detailed Findings\n`);

  for (const sev of severityOrder) {
    const sevFindings = findings.filter(f => f.severity === sev);
    if (sevFindings.length === 0) continue;

    p.push(`### ${severityLabels[sev]}\n`);

    for (const f of sevFindings) {
      p.push(`#### ${f.id}: ${f.title}\n`);
      p.push(`| Field | Value |\n|-------|-------|`);
      p.push(`| **Severity** | ${sev.toUpperCase()}${f.mitigated ? ' (Mitigated)' : ''} |`);
      p.push(`| **Layer** | ${f.layer} |`);
      p.push(`| **OWASP** | ${f.owasp} |`);
      p.push(`| **NIS2** | ${f.nis2} |`);
      if (f.gdpr) p.push(`| **GDPR** | ${f.gdpr} |`);
      if (f.dora) p.push(`| **DORA** | ${f.dora} |`);
      if (f.file) p.push(`| **File** | \`${f.file}\` |`);
      if (f.line) p.push(`| **Line** | ${f.line} |`);
      p.push('');

      if (f.code) {
        p.push(`**Code:**\n\`\`\`\n${f.code}\n\`\`\`\n`);
      }

      if (f.mitigated) {
        p.push(`> \u2705 **Mitigated** — Guard detected at line ${f.guardLine}: \`${f.guardCode}\`\n`);
      }

      p.push(`**Description:** ${f.description}\n`);
      p.push(`**Recommendation:** ${f.recommendation}\n`);
      p.push(`---\n`);
    }
  }

  // L0 Discovery
  p.push(`## L0: Discovery\n`);
  p.push(`| Property | Value |\n|----------|-------|`);
  p.push(`| **Transport** | ${discovery.transports.length ? discovery.transports.join(', ') : 'Not detected'} |`);
  p.push(`| **MCP Tools** | ~${discovery.toolCount} detected |`);
  p.push(`| **Dependency Pinning** | ${discovery.hasDependencyPinning ? '\u2705 Yes' : '\u274C No'} |`);
  p.push(`| **Containerization** | ${discovery.hasContainerization ? '\u2705 Yes' : '\u274C No'} |`);
  if (discovery.dependencies.length > 0) {
    p.push(`| **Dependencies** | ${discovery.dependencies.length} (${discovery.dependencyFile}) |`);
  }
  p.push('');

  if (discovery.dependencies.length > 0) {
    p.push(`<details>\n<summary>Dependency List</summary>\n`);
    for (const dep of discovery.dependencies) {
      p.push(`- ${dep}`);
    }
    p.push(`\n</details>\n`);
  }

  // Footer
  p.push(`---\n`);
  p.push(`## Full Security Assessment\n`);
  p.push(`This scan covers **L0 Discovery + L1 Sandboxing** (${findings.length} findings).\n`);
  p.push(`Production MCP deployments need **knowledge graph-driven analysis** (L2-L4):\n`);
  p.push(`- **L2 Authorization** — RBAC, secret management, JWT/OAuth, PII/GDPR compliance`);
  p.push(`- **L3 Tool Integrity** — SSRF, injection, prompt poisoning, supply chain`);
  p.push(`- **L4 Runtime Monitoring** — audit logging, rate limiting, error leakage\n`);
  p.push(`**49 rules. Full taint tracking. Attack path visualization. OWASP (10/10). NIS2 (7/7). GDPR (6/6). DORA.**\n`);
  p.push(`> [Book a Compuute Security Assessment](https://compuute.se/audit) — knowledge graph analysis, not just pattern matching\n`);
  p.push(`*Generated by compuute-scan v${VERSION} (open source) | Compuute AB*`);

  return p.join('\n');
}

// ─────────────────────────────────────────────
// Report: JSON
// ─────────────────────────────────────────────

function generateJsonReport(repoPath, findings, discovery, durationMs) {
  const repoName = path.basename(path.resolve(repoPath));
  const { summary, layers } = summarizeFindings(findings);

  return JSON.stringify({
    scanner: 'compuute-scan',
    version: VERSION,
    tier: 'open-source',
    layersCovered: ['L0', 'L1'],
    repo: repoName,
    date: new Date().toISOString(),
    filesScanned: discovery.totalSourceFiles,
    scanDurationMs: durationMs,
    summary,
    layers,
    l0Discovery: discovery,
    findings,
    upgrade: {
      message: 'This scan covers L0-L1 (pattern matching). Full L2-L4 assessment uses knowledge graph-driven analysis with taint tracking and attack path visualization.',
      url: 'https://compuute.se/audit',
    },
  }, null, 2);
}

function generateSarifReport(repoPath, findings, discovery, durationMs) {
  const repoName = path.basename(path.resolve(repoPath));

  const severityToSarif = {
    critical: 'error',
    high: 'error',
    medium: 'warning',
    low: 'note',
    info: 'note',
  };

  const rules = [];
  const ruleIndex = {};
  const results = [];

  for (const f of findings) {
    if (!(f.id in ruleIndex)) {
      ruleIndex[f.id] = rules.length;
      rules.push({
        id: f.id,
        name: f.title,
        shortDescription: { text: f.title },
        fullDescription: { text: f.description || f.title },
        helpUri: 'https://compuute.se',
        properties: {
          layer: f.layer,
          owasp: f.owasp || '',
          nis2: f.nis2 || '',
          gdpr: f.gdpr || '',
          dora: f.dora || '',
        },
      });
    }

    if (f.file) {
      results.push({
        ruleId: f.id,
        ruleIndex: ruleIndex[f.id],
        level: severityToSarif[f.severity] || 'warning',
        message: { text: f.recommendation || f.description || f.title },
        locations: [{
          physicalLocation: {
            artifactLocation: { uri: f.file, uriBaseId: '%SRCROOT%' },
            region: { startLine: f.line || 1 },
          },
        }],
        properties: {
          severity: f.severity,
          mitigated: f.mitigated || false,
        },
      });
    }
  }

  return JSON.stringify({
    $schema: 'https://raw.githubusercontent.com/oasis-tcs/sarif-spec/main/sarif-2.1/schema/sarif-schema-2.1.0.json',
    version: '2.1.0',
    runs: [{
      tool: {
        driver: {
          name: 'compuute-scan',
          version: VERSION,
          informationUri: 'https://github.com/Compuute/compuute-scan',
          rules,
        },
      },
      results,
      invocations: [{
        executionSuccessful: true,
        properties: {
          filesScanned: discovery.totalSourceFiles,
          durationMs,
        },
      }],
    }],
  }, null, 2);
}




// ─────────────────────────────────────────────
// Main
// ─────────────────────────────────────────────

function main() {
  const opts = parseArgs(process.argv);

  if (opts.help || !opts.repoPath) {
    printUsage();
    process.exit(opts.help ? 0 : 1);
  }

  const repoPath = path.resolve(opts.repoPath);
  if (!fs.existsSync(repoPath)) {
    console.error(`Error: Path does not exist: ${repoPath}`);
    process.exit(2);
  }

  const startTime = Date.now();

  // Load config
  const config = loadConfig(repoPath);
  if (config && opts.verbose) {
    console.error('Loaded .compuute-scan.json');
  }

  // Walk files (respecting config ignore patterns)
  const allSourceFiles = walkDir(repoPath);
  const sourceFiles = config
    ? allSourceFiles.filter(f => !shouldIgnoreFile(path.relative(repoPath, f), config))
    : allSourceFiles;

  if (opts.verbose) {
    console.error(`Scanning ${sourceFiles.length} files in ${repoPath}...`);
    if (allSourceFiles.length !== sourceFiles.length) {
      console.error(`  (${allSourceFiles.length - sourceFiles.length} files excluded by config)`);
    }
  }

  // Build combined content for negative checks
  const contentParts = [];
  for (const f of sourceFiles) {
    const content = readFileSafe(f);
    if (content) {
      contentParts.push(content);
      if (opts.verbose) {
        console.error(`  ${path.relative(repoPath, f)}`);
      }
    }
  }
  const allContent = contentParts.join('\n');

  // Collect all per-file rules (apply config overrides)
  let allFileRules = [...L1_RULES, ...L2_RULES, ...L3_RULES, ...L4_RULES, ...L4_RULES_EXTRA];
  allFileRules = applyRuleConfig(allFileRules, config);

  // Run per-file scans
  let findings = [];
  for (const f of sourceFiles) {
    const guardWindow = config && config.guardWindow ? config.guardWindow : null;
    const fileFindings = scanFile(f, repoPath, allFileRules, guardWindow);
    findings.push(...fileFindings);
  }

  // Run negative checks (apply config overrides)
  let negativeRules = [...L1_NEGATIVE_RULES, ...L2_NEGATIVE_RULES, ...L3_NEGATIVE_RULES, ...L4_NEGATIVE_RULES];
  negativeRules = applyRuleConfig(negativeRules, config);
  findings.push(...runNegativeChecks(allContent, negativeRules, sourceFiles));

  // L0 Discovery
  const discovery = runL0Discovery(repoPath, allContent, sourceFiles);

  const durationMs = Date.now() - startTime;

  // Apply filters
  if (opts.layer) {
    findings = findings.filter(f => f.layer === opts.layer);
  }
  if (opts.minSeverity) {
    const minOrder = SEVERITY_ORDER[opts.minSeverity];
    if (minOrder !== undefined) {
      findings = findings.filter(f => SEVERITY_ORDER[f.severity] <= minOrder);
    }
  }

  // Sort by severity (critical first)
  findings.sort((a, b) => (SEVERITY_ORDER[a.severity] || 99) - (SEVERITY_ORDER[b.severity] || 99));

  // Generate report
  let report;
  if (opts.sarif) {
    report = generateSarifReport(repoPath, findings, discovery, durationMs);
  } else if (opts.json) {
    report = generateJsonReport(repoPath, findings, discovery, durationMs);
  } else {
    report = generateMarkdownReport(repoPath, findings, discovery, durationMs);
  }

  // Output
  if (opts.output) {
    fs.writeFileSync(opts.output, report);
    console.error(`Report written to ${opts.output}`);
  } else {
    console.log(report);
  }

  // Upgrade notice (stderr so it doesn't pollute report output)
  if (!opts.json && !opts.sarif) {
    console.error('');
    console.error('L0-L1 scan complete. For knowledge graph-driven L2-L4 analysis + compliance mapping:');
    console.error('  https://compuute.se/audit');
  }

  // Determine exit code
  if (opts.failOnSeverity) {
    const threshold = SEVERITY_ORDER[opts.failOnSeverity];
    if (threshold !== undefined) {
      const hasFindings = findings.some(f => SEVERITY_ORDER[f.severity] <= threshold);
      if (hasFindings) {
        console.error(`\nFindings at or above "${opts.failOnSeverity}" severity detected — exiting with code 1.`);
        process.exit(1);
      }
    }
  }

  process.exit(0);
}

main();
