#!/usr/bin/env node
// Build script: concatenates src/ modules into compuute-scan.js
// Output is a single zero-dependency file that works with npx.
//
// Usage: node scripts/build.js

'use strict';

const fs = require('fs');
const path = require('path');

const SRC_DIR = path.join(__dirname, '..', 'src');
const OUTPUT = path.join(__dirname, '..', 'compuute-scan.js');

// Module order matters — later modules depend on earlier ones
const MODULES = [
  'constants.js',
  'config.js',
  'cli.js',
  'walker.js',
  'guards.js',
  'rules-l1.js',
  'rules-l2l4.js',
  'discovery.js',
  'dependency-checks.js',
  'engine.js',
  'reporters.js',
  'main.js',
];

const HEADER = `#!/usr/bin/env node
// compuute-scan v0.6.0 — MCP Server Security Scanner
// Compuute AB | daniel@compuute.se
// Zero external dependencies. Node.js built-ins only.
//
// Built from src/ modules by scripts/build.js
// Do not edit this file directly — edit src/*.js and run: npm run build

'use strict';

const fs = require('fs');
const path = require('path');
`;

const parts = [HEADER];

for (const mod of MODULES) {
  const filePath = path.join(SRC_DIR, mod);
  if (!fs.existsSync(filePath)) {
    console.error(`ERROR: Missing module: ${filePath}`);
    process.exit(1);
  }
  const content = fs.readFileSync(filePath, 'utf-8');
  parts.push(`\n${content}`);
}

const output = parts.join('\n');
fs.writeFileSync(OUTPUT, output);

// Verify the output runs
const { execFileSync } = require('child_process');
try {
  execFileSync('node', [OUTPUT, '--help'], { stdio: 'pipe', timeout: 5000 });
  console.log(`Built: ${OUTPUT} (${output.split('\n').length} lines)`);
} catch (err) {
  console.error('ERROR: Built file fails to execute:');
  console.error(err.stderr?.toString() || err.message);
  process.exit(1);
}

// Copy to web UI lib
const webCopy = path.join(__dirname, '..', 'death-by-mcp', 'lib', 'compuute-scan.js');
if (fs.existsSync(path.dirname(webCopy))) {
  fs.writeFileSync(webCopy, output);
  console.log(`Synced: ${webCopy}`);
}

console.log('Build complete.');
